---
title: "Life Expectancy vs healthcare"
author: "Duc-Quang Nguyen | swissinfo.ch"
date: "27 Sept 2016"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: simplex
---

## Related

* [financing-healthcare/](https://ourworldindata.org/financing-healthcare/)
* [life-expectancy-and-health-spending](https://ourworldindata.org/the-link-between-life-expectancy-and-health-spending-us-focus)

* [tweenr github example](https://github.com/thomasp85/tweenr)
* [tweenr tutorial](http://lenkiefer.com/2016/05/29/improving-R-animated-gifs-with-tweenr)
* [gganimate](https://github.com/dgrtwo/gganimate)

## Data

* [OECD all health stuff](http://www.oecd.org/els/health-systems/Table-of-Content-Metadata-OECD-Health-Statistics-2016.pdf)
* [OECD health expenditure](http://stats.oecd.org/viewhtml.aspx?datasetcode=SHA&lang=en)
# [World bank](http://data.worldbank.org/indicator/SH.XPD.PCAP.PP.KD)
* [Commonwelath fund CH profile](http://international.commonwealthfund.org/countries/switzerland/)
* [Health Care Spending as a Percentage of GDP](http://www.commonwealthfund.org/interactives-and-data/chart-cart/chartbook/multinational-comparisons-data-2014/health-care-spending-as-a-percentage-of-gdp)
* [HALE](http://apps.who.int/gho/data/view.main.HALEXv?lang=en)


```{r setup, include=FALSE}
testGif <- F
downloadData <- F
plotTest <- F

ani.interval <- 1/5



translation.file <- "input/healthcare expenditure vs life expectancy - Sheet1.csv"

#iso3.sub <- c("NOR", "CHE", "ITA", "FRA", "JPN", "GBR", "ESP", "USA", "CHN", "IND", "BRA", "RUS")

iso3.sub <- c("CHE", "FRA", "JPN", "KOR", "GBR", "ESP", "PRT", "USA", "DEU", "CAN", "SWE", "TUR")
iso3.sub <- c("CHE", "FRA", "JPN", "GBR", "ESP", "USA", "DEU")

health.datafile <- "input/healthExpenditure_oecd.csv"
le.datafife <- "input/lifeExpectancy_wb.csv"

library(readr)
library(tidyr)
library(dplyr)
library(magrittr)
library(countrycode)
library(ggplot2)
library(scales)
library(swiMap)
library(swiTheme)
library(forcats)

### Getting data in packages

library(WDI)
library(OECD)

#library(ggrepel)
library(tweenr)
library(gganimate)

```


```{r get data}
if(downloadData) {
  ## get health expenditure data
  
  # dsets <- get_datasets()
  # search_dataset("health", dsets)
  dst <- get_data_structure( 'SHA')
  data.read <- get_dataset(oecd.idtb, filter = list("HFTOT", "HCTOT", "HPTOT", 'VRPPPR'))
  data.read$obsTime <- as.numeric(data.read$obsTime)
  
  he.data <- data.read %>% select(-HF, -HC, -HP, -MEASURE, -TIME_FORMAT, -POWERCODE, -UNIT)
  write_csv(he.data, path = health.datafile)
  
  # get life expectancy data
  data.dl <- WDI(
    indicator = 'SP.DYN.LE00.IN',
    start = 1950,  
    end = 2016, 
    extra = TRUE, 
    cache = NULL
  )
  colnames(data.dl)[3] <- 'value'
  le.data <- data.dl %>% select(-capital, -longitude, -latitude, -lending)
  
  write_csv(le.data, path = le.datafife)  
} else {
  he.data <- read_csv(health.datafile)
  le.data <- read_csv(le.datafife)
  
  txt <- loadTranslation(translation.file)
}
```

```{r merge & wrangle}
df1 <- he.data %>% 
  rename(he = obsValue, iso3c = LOCATION, year = obsTime) %>% 
  select(-REFERENCEPERIOD)
df2 <- le.data %>% rename(le = value)

df.all <- right_join(df1, df2)  
df <- df.all %>% filter(iso3c %in% iso3.sub)

# remove row with NA he or le
#df <- df[which(!(is.na(df$he) | is.na(df$le))),] %>% arrange(year)
df %>% group_by(iso3c) %>% summarise(nVal = length(he) )

# test plot
ylim <-  c(70, 85)
xlim <- c(0, 9500)

# remove rows with both NA values
df.lab <- df[which((!is.na(df$he) & !is.na(df$le))),] %>% arrange(year)

```


```{r plot helper, echo = F}
sTheme <- function(
  base_size = 18, 
  base_family = "OpenSans-CondensedLight", 
  title_family = "OpenSans-CondensedBold", 
  subtitle = "OpenSans-CondensedLight"
) {
  swi_theme(base_size = base_size, title_family = title_family, subtitle = subtitle, base_family = base_family) + 
  theme(
    plot.title = element_text(family = title_family, size = base_size * 1.3, margin=margin(b=13), lineheight = 0.8),
    plot.caption = element_text(size = base_size * 0.6, hjust=0, margin=margin(t=13), face = "italic"),
    axis.line.y = element_blank(), 
    legend.position = "none"
    ) 
}

gp <- ggplot(df, aes(x = he, y = le)) + 
  geom_line(aes(group = iso2c, colour = iso2c), size = 0.1) + 
  geom_text(data = subset(df.lab, year == max(year)), aes(label = country), 
            nudge_x = 100) +
  sTheme() + 
      geom_smooth(size = 0.2, method = "loess") +
  geom_label(
    aes(x = 0, y = 85, label="Life Expectancy"), size = 5,
    family = "OpenSans-CondensedLight", label.size = 0, nudge_x = 110
  ) + 
  theme(axis.line.y = element_blank()) + 
    geom_point(aes(group = iso2c, colour = iso2c), size = 0.5) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10), limits = xlim,
                     name = "Health expenditure by capita\n(adjusted for inflation, at PPP in 2010 USD)") +
  scale_y_continuous(limits = ylim, name = "Life Expectancy") + 
  scale_color_manual(values = swi_rpal)
if(plotTest) gp

tRange <- df.all %>% group_by(iso2c, iso3c, country) %>% 
  summarise(start = min(year[which(!is.na(he) & !is.na(le))]), 
            end = max(year[which(!is.na(he) & !is.na(le))])
  ) %>% ungroup()
tRange <- tRange[is.finite(tRange$start),] %>% as.data.frame()


gp2 <- ggplot(df.all, aes(x = he, y = le)) + 
  geom_line(aes(group = iso2c), size = 0.1, colour = "grey") + 
  sTheme() + theme(plot.margin = unit(c(0.3, 0, 0.3, 0.3), "lines")) +
  theme(axis.line.y = element_blank()) + 
    geom_smooth(size = 0.2, method = "loess") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10), limits = xlim,
                     name = "Health expenditure by capita\n(adjusted for inflation, at PPP in 2010 USD)") +
  scale_y_continuous(limits = c(50, 85)) 
if(plotTest) gp2

```

```{r tweenr}
dd <- df %>% select(-region, -income, -iso3c, -OBS_STATUS, -indicator)
dd$country <- as.factor(dd$country)
dd$iso2c <- as.factor(dd$iso2c)

if(testGif) {
  warning("\n data will be slashed to create a smaller gif")
  dd <- dd %>% filter(year >= 2004)
  txt <- txt[, 1, drop = F]
}

# for each country find the years where both he and le are defined
years <- by(dd, dd$iso2c, function(ddd) ddd[which(!is.na(ddd$he) & !is.na(ddd$le)),'year'] ) %>% 
  unlist(use.names = F) %>% unique() %>% sort()
dd %<>% filter(year %in% years)
dd$col <- swi_rpal[-c(3,5,7, 11)][dd$iso2c]

# create a data.frame with start, end values
tRanges <- dd %>% group_by(iso2c, country) %>% 
  filter(!is.na(he) & !is.na(le)) %>% arrange(year) %>%
  summarise(tStart = first(year), tEnd = last(year)) %>%
  ungroup()
  
if(length(unique(tRanges$tStart)) > 1 || length(unique(tRanges$tEnd)) > 1) {
  stop()
}
tRanges <- range(tRanges$tStart, tRanges$tEnd)

dd.seg <- dd %>% filter(year %in% tRanges) %>% arrange(year) %>%
  group_by(iso2c, country, col) %>% 
  summarise(x = first(he), xend = last(he), y = first(le), yend = last(le)) %>%
  ungroup()

dd.point <- dd %>% filter(year %in% tRanges)
# create a list of data frame for each year

ddd <- split(dd.point, dd.point$year)
ddd <- c(ddd, rep(ddd[length(ddd)], 2), ddd[1])

tf <- tween_states(
  ddd, tweenlength = 1, statelength = 1.2, 
  ease = c('quadratic-in-out'), nframes = 50
) 
time.lab <- tf %>% select(year, .frame) %>% filter(year %in% tRanges)
time.lab <- time.lab[!duplicated(time.lab),]
time.lab$x <- 9450
time.lab$y <- 70
tf <- tf %<>% select(-year)

for(lang in colnames(txt)) {

  dddd <- tf
  outfile <-  paste0("01_connectedScatter_healthcareEvsLifeE_", lang, ifelse(testGif, "_test", ""), ".gif")
  
  dddd$label <- countryTranslation(as.character(dddd$iso2c), lang)[,-1]
  if(any(is.na(dddd$label))) {
    stop("\nSome country translations are missing!")
  }
  dddd.label <- dddd %>% group_by(label, iso2c) %>%
    summarise(he = max(he), le = max(le)) %>%
    ungroup()
  dddd.label <- cbind(dddd.label, dd.seg[match(dddd.label$iso2c, dd.seg$iso2c), 'col'])
    
  footer2 <- paste0("\n", txt['footer.b', lang], " ", txt['footer.c', lang])
  footer2 <- paste0(strwrap(footer2, width = 168, prefix = "\n"), collapse = "")
   
  p <- ggplot(
    data = dddd, 
    aes(x = he, y = le)
  ) + 
    geom_text( 
      data = dddd.label,
      aes(label = label, colour = col), hjust = 0, 
      nudge_x = 61, nudge_xnudge_y = 1.2, alpha = 1,
      family = txt['base.font', lang], size = 7
    ) + 
    geom_segment(
      data = dd.seg, 
      aes(x = x, xend = xend, y = y, yend = yend, 
          group = iso2c, colour = col), size = 0.1, alpha = 0.9
    ) +
    geom_line(data = dd,
      aes(x = he, y = le, group = iso2c, colour = col), 
      size = 0.3, linetype = "dashed", alpha = 1
    ) + 
    geom_point(aes(colour = col, group = iso2c, frame = .frame), size = 5, shape = 18, alpha = 1) +
    geom_text(
      data = time.lab, aes(x = x, y = y, label = year, frame  = .frame),
      size = 88, hjust = 1, vjust = 0, family = txt['title.font', lang],
      colour = "#e5dbcd", alpha = 0.5)   +
    sTheme(
      base_size = 26, base_family = txt['base.font', lang], 
      title_family =  txt['title.font', lang], 
      subtitle = txt['base.font', lang]
    ) +
    theme(
      plot.margin = unit(c(0.3, 1.5, 0.2, 0.7), "lines")#,
      #plot.subtitle=element_text(size = 9)
      ) +
    scale_x_continuous(
      breaks = scales::pretty_breaks(n = 10),
      limits = xlim,
      labels = scales::dollar,
      expand = c(0, 0.1),
      name = paste0(txt["x.lab", lang], "\n", txt["x.lab2", lang])) +
    scale_y_continuous(
      limits = ylim, name = txt["y.lab", lang], 
      breaks = scales::pretty_breaks(n = 10)
    ) +
    scale_colour_identity() + 
    labs(
      title = paste0(strwrap(txt['main.title', lang], width = as.numeric(txt['title.width', lang]), 
        prefix = "\n", initial = ""), collapse = ""),
      subtitle =  txt['descr', lang],
      caption = paste0(txt['source', lang], ": ", txt['source.name', lang], " | ", txt['footer.a', lang], " | swissinfo.ch", "\n", footer2)
    )
  
  animation::ani.options(interval = ani.interval)
  gg_animate(p, outfile, title_frame = F, ani.width = 640 * 1.5, 
             ani.height = 650 * 1.5)

  # move to output
  file.rename(from = outfile, to = paste0("output/", outfile))
}





```

```