---
title: "Life Expectancy vs healthcare"
author: "Duc-Quang Nguyen | swissinfo.ch"
date: "10 Oct 2016"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: simplex
---


```{r setup, include=FALSE}
downloadData <- F

#iso3.sub <- c("NOR", "CHE", "ITA", "FRA", "JPN", "GBR", "ESP", "USA", "CHN", "IND", "BRA", "RUS")
# iso3.sub <- c("CHE", "ITA", "FRA", "JPN", "GBR", "ESP", "USA", "CHN", "DEU", "CAN")
# iso3.sub <- c("CHE", "FRA", "JPN", "KOR", "GBR", "ESP", "PRT", "USA", "DEU", "CAN", "SWE", "TUR")

wb.indicators <- c('SP.DYN.LE00.IN', 'SH.XPD.PCAP.PP.KD', 'NY.GDP.PCAP.PP.KD')
health.datafile <- "input/healthExpenditure_wb.csv"
le.datafife <- "input/lifeExpectancy_wb.csv"
gdp.datafile <- "input/gdpPerCapita_PPP_constant2011USD.csv"

library(readr)
library(tidyr)
library(dplyr)
library(magrittr)
library(countrycode)
library(ggplot2)
library(scales)
library(swiMap)
library(swiTheme)
library(forcats)

### Getting data in packages

library(WDI)

library(forcats)

### Interactive 
library(htmltools)
library(shiny)
library(swiRcharts)
library(rCharts)
library(highcharter)

library(viridisLite)
```


```{r get data}
if(downloadData) {

  #helper
  getWBdata <- function(ind.code, ind.name = NULL) {
    if(is.null(ind.name)) { ind.name <- ind.code }
    data.dl <- WDI(
      indicator = ind.code,
      start = 1950,  
      end = 2016, 
      extra = TRUE, 
      cache = NULL
    )
    colnames(data.dl)[3] <- 'value'
    data.dl$indicator <- ind.name
    data.dl %>% select(-capital, -longitude, -latitude, -lending)
  }
  
  ## get health expenditure data from WB http://data.worldbank.org/indicator/SH.XPD.PCAP.PP.KD
  he.data <- getWBdata(wb.indicators[2])
  write_csv(he.data, path = health.datafile)
  
  # get life expectancy data
  le.data <- getWBdata(wb.indicators[1])
  write_csv(le.data, path = le.datafife)  
  
  # get GDP per capita
  gdp.data <- getWBdata(wb.indicators[3])
  write_csv(gdp.data, path = gdp.datafile)   
  
} else {
  he.data <- read_csv(health.datafile)
  le.data <- read_csv(le.datafife)
  gdp.data <- read_csv(gdp.datafile)
}
```

```{r merge & wrangle}

df.all <- right_join(
  he.data %>% rename(he = value) %>% select(-region, -income, -indicator), 
  le.data %>% rename(le = value) %>% select(-region, -income, -indicator)
  )  
df.all <- right_join(
  df.all, 
  gdp.data %>% rename(gdp = value) %>% select(-region, -income, -indicator)
)

df.all <- df.all %>% arrange(year)
# remove NA rows
df.all <- df.all[-which(is.na(df.all$he) & is.na(df.all$le) & is.na(df.all$gdp)), ]

# select only the last year with value for 3 indicators
# http://stackoverflow.com/questions/23340150/using-dplyr-window-functions-to-make-trailing-values-fill-in-na-values
df <- df.all %>% group_by(country, iso2c, iso3c) %>%
  fill(he) %>% fill(le) %>% fill(gdp) %>% 
  summarise(he = last(he), le = last(le), gdp = last(gdp)) %>%
  ungroup()

# remove rows with one or more NA
df <- df[-which(is.na(df$he) | is.na(df$le) | is.na(df$gdp)), ]

df$region <- countrycode(df$iso2c, "iso2c", "continent")
df <- df[which(!is.na(df$region)),]
```


```{r interactive chart}


dd <- df 

hSeries <- hSeries2(
  data.frame(
    x = dd$he,
    y = dd$le,
    z = dd$gdp,
    color = colorize_vector(dd$region, "A"),
    name = dd$country,
    series = dd$iso2c
  ), 
  "series")

bc <- highchart(height = 580) %>%
  hc_chart(type = "bubble", spacing = c(7, 4, 4, 0)) %>%
  hc_add_series_list(hSeries) %>% 
  hc_tooltip(
    formatter = JS("function() { return this.point.name;}"), 
    useHTML = TRUE,
    borderWidth = 2
  ) %>%
  hc_plotOptions(bubble = list(maxSize = "7%")) %>%
  hc_legend(enabled = F) %>% hc_add_theme(hc_theme_swi)

bc %<>%  hc_yAxis(
  title = list(text = txt['y.title', lang]),
  floor = 500,
  opposite = ifelse(lang == "AR", TRUE, FALSE)
) %>%
  hc_xAxis(title = list(text = txt['x.title', lang]), 
           reversed = ifelse(lang == "AR", TRUE, FALSE)) %>%
  hc_plotOptions(
    bubble = list(
      dataLabels = list(
        enabled = T, 
        format = '{series.name}', 
        style = list(
          textShadow = F,
          fontSize = "0.8em",
          fontWeight = "normal"
        )
      )),
    line = list(marker = list(enabled = FALSE), lineWidth = 1, dashStyle = "dash")
  )
  
  

```