---
title: ""
author: "Duc-Quang Nguyen | swissinfo.ch"
date: " 2016"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: simplex
---

```{r setup, include=FALSE}
health.datafile <- "input/healthExpenditure_oecd.csv"
le.datafife <- "input/lifeExpectancy_wb.csv"


library(readr)
library(tidyr)
library(dplyr)
library(magrittr)
library(countrycode)
library(ggplot2)
library(scales)
library(swiMap)
library(swiTheme)
library(forcats)

### Interactive 
library(htmltools)
library(shiny)
library(swiRcharts)
library(rCharts)
library(highcharter)

library(viridisLite)

```

```{r get data}
he.data <- read_csv(health.datafile)
le.data <- read_csv(le.datafife)

df1 <- he.data %>% 
  rename(he = obsValue, iso3c = LOCATION, year = obsTime) %>% 
  select(-REFERENCEPERIOD)
df2 <- le.data %>% rename(le = value)

df.all <- right_join(df1, df2)  

#remove row with NA he or le
df.all <- df.all[which(!(is.na(df.all$he) | is.na(df.all$le))),] %>% arrange(year)  

# get only the last value 
df <- df.all %>% group_by(iso3c, iso2c, country) %>%
  summarise(he = last(he), le = last(le), year = last(year)) %>% ungroup()
dd <- df

hSeries <- hSeries2(
  data.frame(
    x = dd$he,
    y = dd$le,
    # z = dd$nPlayers,
    # color = colorize_vector(-dd$gdp, "A"),
    name = dd$country,
    series = dd$iso2c
  ), 
  "series")

bc <- highchart(height = 580) %>%
  hc_chart(type = "bubble", spacing = c(7, 4, 4, 0)) %>%
  hc_add_series_list(hSeries) %>% 
  hc_tooltip(
    formatter = JS("function() { return this.point.name;}"), 
    useHTML = TRUE,
    borderWidth = 2
  ) %>%
  hc_plotOptions(bubble = list(maxSize = "5%")) %>%
  hc_legend(enabled = F) %>% hc_add_theme(hc_theme_swi)

  


```