---
title: "09_explore_primeMaladie2017"
author: "Duc-Quang Nguyen"
date: "10/14/2016"
output: html_document
---

# Data

* [Primes de l’assurance-maladie](https://opendata.swiss/fr/dataset/health-insurance-premiums)



```{r setup, include=FALSE}

data.file <- "data/Prämien_CH.csv"
insurer.file <- "data/insurer_CH_01_10_2016.csv"

library(readr)
library(tidyr)
library(dplyr)
library(magrittr)
library(countrycode)
library(ggplot2)
library(swiMap)
library(swiTheme)
library(forcats)

library(forcats)
library(viridis)
library(ggiraph)

library(htmltools)
library(swiRcharts)


```

```{r load data}
data.read <- read.csv(data.file)
insurer <- read.csv(insurer.file)

# basic exploration
#lapply(data.read, unique)

data.read <- data.read %>% select(-Hoheitsgebiet, -Geschäftsjahr, -Erhebungsjahr)

# select: tarif : BASE (not HMO, ..)
# sans assurance accident, adultes, franchise 500.-
dd <- data.read %>% filter(Tarif == "BASE", Unfalleinschluss == "OHN-UNF", 
                           Altersklasse == 'AKL-ERW', Franchise == 'FRA-500', Kanton != "ZE")

# order canton by average prime 
ddd <- dd %>% group_by(Kanton, Versicherer) %>% 
  summarise(prime = mean(Prämie)) %>% ungroup()
ct.ordered <- ddd %>% group_by(Kanton) %>% summarise(meanPrime = mean(prime)) %>% 
  ungroup() %>% arrange(meanPrime) %>% select(Kanton) %>% unlist(use.names = F) %>% as.character()
ddd$Kanton <- factor(ddd$Kanton, levels = ct.ordered)

# order insurer by average prime
insurer.ordered <- ddd %>% group_by(Kanton) %>% mutate( rk = rank(prime)) %>% ungroup()
insurer.rank <- insurer.ordered %>% group_by(Versicherer) %>% summarise(meanRank = mean(rk)) %>% 
  ungroup() %>% arrange(meanRank)
insurer.ordered <- insurer.rank %>% select(Versicherer)  %>% unlist(use.names = F)

names(insurer.ordered) <- insurer[match(insurer.ordered, insurer[,1]), 'shortName']
ddd$insurerName <- factor(insurer[match(ddd$Versicherer,  insurer[,1]), 'shortName'], levels = names(insurer.ordered))
ddd$insurerRank <- insurer.rank[match(ddd$Versicherer, insurer.rank$Versicherer), 'meanRank'] %>% unlist(use.names = F)

ddd$canton <- canton_CH[match(ddd$Kanton, canton_CH$iso2), 'intl']
ddd$canton <- factor(ddd$canton, canton_CH[match(ct.ordered, canton_CH$iso2), 'intl'])


gp <- ggplot(data = ddd) + 
 # geom_violin(aes(x = canton, y = prime, group = canton), linetype = "blank", fill = "#e5dbcd", alpha = 0.6) + 
  geom_line(data = ddd %>% group_by(canton) %>% summarise(prime = median(prime)) %>% 
              ungroup(), aes(x = canton, y = prime, group = 1), size = 0.6, alpha = 0.5, colour = "darkgrey") + 
  geom_line_interactive(aes(x = canton, y = prime, group = insurerName, color = insurerRank, tooltip = insurerName, data_id = insurerName), size = 0.2, alpha = 0.25) + 
  geom_point_interactive(aes(x = canton, y = prime, group = insurerName, color = insurerRank, data_id = insurerName, tooltip = insurerName), size = 0.7, alpha = 0.5, shape = 18) + 
  geom_text(data  = ddd %>% filter(Kanton == "GE"), aes(x = canton, y = prime, label = insurerName), nudge_y = -1, nudge_x = 0.35, hjust = 0, size = 1.9, family = "Open Sans Condensed", check_overlap = T, colour = "#595959") +
  swi_theme(y_gridlines = F, base_size = 12, base_family = "Open Sans Condensed") + 
  theme(
    legend.position = "none", 
    axis.text.x = element_text(angle = -90, hjust = 0, vjust = 0.5), 
    axis.text.y = element_text(margin=margin(0,-1.5,0,0) ),
    plot.background=element_rect(fill= "#f3f3f2", colour = "#f3f3f2")
  )+
  scale_color_viridis(option = "B") +
  scale_x_discrete(expand = c(-1, 2.2), name = "") +
  scale_y_continuous(name = "", expand = c(0.005,0.05), breaks = scales::pretty_breaks(n =5)) +
  geom_text(aes(x = -1, y = 700, label="Primes mensuels (CHF)"), colour = "#2b2b2b", hjust = 0)

  #geom_point_interactive(aes(x = Kanton, y = prime, group = insurerName, color = insurerRank, tooltip = prime, data_id = insurerName), size = 0.2, alpha = 0.8)
igp <- ggiraph(
  code = {print(gp)}, 
  height_svg = 7,
  hover_css = "stroke-width:1.7px;stroke-opacity:0.95;cursor:pointer;",  
  width = 1,
  fonts = list(sans = "Open Sans Condensed")
)
igp

lang <- 'FR'
save_html(
  tags$html(
    tags$head(includeHTML("styles2.html")),
    tags$body(    
      h2("Assurance maladie de base - la valse des tarifs pour des prestations identiques par tous les assureurs"),#txt["main.title", lang]),
      div(class = "descr", HTML(paste0("Tarifs mensuels de l'assurance maladie de base 2017 par canton et par assureur. Pour un adulte, sans couverture d'assurance accident et une franchise de 500.-. Pour les cantons ayant différent tarifs selon les régions, la moyenne cantonale par assureur a été calculée."))),
      div(class="container", igp),
      HTML(iframeresizer)  
    )), file = paste0("Primes_2017_byCantonInsurer_", lang, ".html"), libdir = "js", background = "#f3f3f2"
)

  
```